---

- hosts: servers
  become: true
  tasks:
         
  - name: Install Apache and libapache2 piackage.
    package:
      name: 
        - "{{ Apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

