---

- hosts: servers
  become: true
  tasks:

  - name: Update repo
    apt:
     update_cache: yes
          
  - name: Install Apache package.
    apt:
      name: apache2
      state: latest

  - name: Add php support for Apache
    apt:
     name: libapache2-mod-php
     state: latest
