---

- hosts: servers
  become: true
  tasks:
         
  - name: Install Apache and libapache2 piackage.
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

